apiVersion: v1
kind: Pod
metadata:
  name: bigdl-fschat-a1234bd-controller
  labels:
    fastchat-appid: a1234bd
    fastchat-app-type: controller
spec:
  hostNetwork: True
  dnsPolicy: "ClusterFirst"
  containers:
  - name: fastchat-controller # fixed
    image: "intelanalytics/bigdl-ppml-trusted-fastchat-tdx:2.4.0-SNAPSHOT"
    imagePullPolicy: Always
    env:
    - name: CONTROLLER_ADDRESS # fixed
      value: bigdl-a1234bd-fschat-controller-service
    - name: CONTROLLER_PORT # fixed
      value: 21005
    - name: API_HOST # fixed
      value: bigdl-a1234bd-fschat-controller-service
    - name: API_PORT # fixed
      value: 8000
    ports:
      - containerPort: $(CONTROLLER_PORT)
        name: fastchat-controller-port
      - containerPort: $(API_PORT)
        name: fastchat-API-port
    resources:
      requests:
        memory: 32Gi
        cpu: 8
      limits:
        memory: 32Gi
        cpu: 8
    args: ["-m controller"]
  restartPolicy: "Never"
---
# Service for the controller
apiVersion: v1
kind: Service
metadata:
  name: bigdl-a1234bd-fschat-controller-service
spec:
  selector:
    fastchat-appid: a1234bd
    fastchat-app-type: controller
  ports:
    - protocol: TCP
      port: 21005
      targetPort: fastchat-controller-port
    - protocol: TCP
      port: 8000 
      targetPort: fastchat-API-port
---
# Worker
apiVersion: v1
kind: Pod
metadata:
  name: bigdl-fschat-a1234bd-worker-1
  labels:
    bigdl-app: a1234bd
    bigdl-app-type: worker
spec:
  dnsPolicy: "ClusterFirst"
  containers:
  - name: fastchat-worker # fixed
    image: "intelanalytics/bigdl-ppml-trusted-fastchat-tdx:2.4.0-SNAPSHOT"
    imagePullPolicy: Always
    env:
    - name: CONTROLLER_ADDRESS # fixed
      value: bigdl-a1234bd-fschat-controller-service
    - name: CONTROLLER_PORT # fixed
      value: 21005
    - name: WORKER_HOST # fixed
      value: "0.0.0.0"
    - name: WORKER_PORT # fixed
      value: "21841"
    resources:
      requests:
        memory: 32Gi
        cpu: 32
      limits:
        memory: 32Gi
        cpu: 32
    args: ["-m worker"]
    volumeMounts:
      - name: ppml-models
      mountPath: /ppml/models/
  restartPolicy: "Never"
  volumes:
  - name: ppml-models
    hostPath:
      path: /root/guancheng/chatllm/models # change this in other envs
